### ISSUE TITLE
Intake ripping cubes

### ISSUE THREAD

**Issue by jacueblol** [Patribots4738/2023-Summer-Robot#10]

**Comment by jacueblol** [comment]
This is clearly an issue and I dont know how I should fix this, maybe lower the speeds? However I have a feeling something else is at play, what do you think @GalexY727

**Comment by GalexY727** [comment]
This is a product of having high current limits

**Comment by GalexY727** [comment]
The claw should stop softly when there is a cube in, which is accomplished on Jerome with a stall current limit of 15

**Comment by GalexY727** [comment]
Maybe should be lesser (7?) due to us having two motors

**Comment by jacueblol** [comment]
Are you able to quickly add in that stall current? (I like having 7 or somewhere in between) I'm about to go out to eat, and If you could quickly do that, it would be a big help. (dont forget to reference the issue num: 10) @GalexY727

**Comment by jacueblol** [comment]
Btw, if you think that the updated values for the speeds: ’0.3’ may interfere with the current limit, you can revert that back to ’0.5’

**Comment by GalexY727** [comment]
Just cuz we have a high current doesn't mean we should have fast speeds. A combination of both being lower would give us the smallest chance to pop a cube.

**Comment by GalexY727** [comment]
The only issue is we still want to transition between stalling and super outtaking

**Comment by jacueblol** [comment]
> The only issue is we still want to transition between stalling and super outtaking

How would you suggest we do that?
