### ISSUE TITLE
Auto shakes back and forth?

### ISSUE THREAD

**Issue by jacueblol** [Patribots4738/2023-Summer-Robot#7]
No Idea why Auto doesn't work, it is still a mystery, possibly this was fixed by setting the new position of the bot to the start of the path?

**Comment by GalexY727** [comment]
I would recommend looking at 971's repository... somewhere (i have no clue where that is unfortunately) as they are the only tank drive bot that I know in charged up that would most likely be using pathplanner

**Comment by GalexY727** [comment]
of course you can find other tank bots by just cruising through world's matches and seeing which one goes neroom

**Comment by jacueblol** [comment]
Thank you for the advice!! Ill try to take a look later tonight or tomorrow morning

**Comment by PatribotsProgramming** [comment]
#8

**Comment by GalexY727** [comment]
The issue ended up being that relative encoder position conversion factors were never being applied due to restorefactorydefaults being called after the factors were applied
